[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Randy Wahdin"
authors = [{name = "Randy Wahidin", email = "killerx@randydev.my.id"}]
dynamic = ["version", "description"]
